---
#become: true
#tasks:

  - name: Install Apache
    ansible.builtin.apt:
      name: apache2
      state: present
    become: true

  - name: Configure index.html
    ansible.builtin.template:
      src: index.html.j2
      dest: /var/www/html/index.html
      owner: www-data
      group: www-data
      mode: '0644'
    notify: Restart Apache
    become: true

  - name: Open port 80
    ansible.builtin.ufw:
      rule: allow
      port: 80
      proto: tcp
    become: true

  - name: Start Apache and enable on boot
    ansible.builtin.service:
      name: apache2
      state: started
      enabled: true
    become: true

  - name: Check website availability
    ansible.builtin.uri:
      url: http://{{ ansible_default_ipv4.address }}
      status_code: 200
    delegate_to: localhost
    run_once: true
  
